
spring.application.name=api-cmi
spring.datasource.url=jdbc:mysql://mysql-865f9d6-kawtarchafiki17-bd96.k.aivencloud.com:18381/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Optional: Configuration for connection pooling
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.pool-name=HikariPool-1

# Optional: Hibernate dialect for MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8085
